version: '3.8'

volumes:
  grafana-storage:
  prometheus-storage:

services:
  influxdb:
      image: influxdb:1.8
      container_name: influxdb
      volumes:
          - type: bind
            source: ./influxdb/influxdb.conf
            target: /etc/influxdb/influxdb.conf
            read_only: true
          - type: bind
            source: ./influxdb/
            target: /var/lib/influxdb
      ports:
          - "8086:8086"

  telegraf:
      image: telegraf:latest
      container_name: telegraf
      restart: always
      volumes:
          - type: bind
            source: ./telegraf/telegraf.conf
            target: /etc/telegraf/telegraf.conf
            read_only: true
      depends_on:
          - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    volumes:
      - './grafana/provisioning:/etc/grafana/provisioning'
      - './grafana/dashboards:/var/lib/grafana/dashboards'
      - 'grafana-storage:/var/lib/grafana'
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel, natel-plotly-panel, blackmirror1-singlestat-math-panel, btplc-trend-box-panel, marcuscalidus-svg-panel, michaeldmoore-multistat-panel, yesoreyeram-boomtable-panel, ryantxu-ajax-panel, grafana-influxdb-flux-datasource, fetzerch-sunandmoon-datasource, andig-darksky-datasource, simpod-json-datasource"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus/pc_auth.env:/etc/prometheus/prometheus.yml'
      - 'prometheus-storage:/prometheus'

  pcc_collector:
    image: collector:dev
    container_name: pcc_collector
    hostname: pcc_collector
